// -----------------------------------------------------------------------------------------------------------------------------
/*  Definition: The Schema for the Pics collection the in mongoDB datatbase

    Fields:
      _id:                The mongoDB autogenerated id of the user.
      ownerID:            The id of the user who's picture it belongs to.
      ownerUsername:      The username of the user who's picture it belongs to.
      img:                The name of the image.
      date:               The date the image was posted to the Database.
      caption:            The caption written by the user belonging to the image.
      likes:              Array containing the id's of all users who liked the photo.
      comments:           Array containing the usernames and comments of the users who commented on the photo.
*/
// -----------------------------------------------------------------------------------------------------------------------------
mongoose = require('mongoose');

PicsSchema = mongoose.Schema({

  ownerID:{
    type: String,
    required: true
  },
  ownerUsername:{
    type: String,
    required: true
  },
  img:{
   imgName: String,
   contentType:String,
  },
  date:{
    type:String,
    required: true
  },
  caption:{
    type:Array,
    required: false
  },
  likes:{
    type:Array,
    required: false
  },
 comments:{
   type:Array,
   required: false
 }
});

let Pics = module.exports = mongoose.model('Pics',PicsSchema);
